apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      color: blue
      dept: test
  template:
    metadata:
      labels:
        color: blue
        dept: test
    spec:
      containers:
        - name: nginx
          image: nginx:1.25.2

# to check nginx version in pod kubectl exec  pod-name -- nginx -v
# to get pod-name kubectl get pods -o wide