apiVersion: apps/v1
kind: Deployment
metadata:
  name: green
spec:
  replicas: 2
  selector:
    matchLabels:
      color: green
      dept: test
  template:
    metadata:
      labels:
        color: green
        dept: test
    spec:
      containers:
        - name: nginx
          image: nginx